syntax = "proto3";

package vela.table;

// 桌子状态
enum TableState {
    TABLE_IDLE = 0; // 桌子空闲(空闲+所有人准备，切换至游戏开始)
    TABLE_GAMING = 1; // 桌子正在游戏中
}

// 桌子信息
message Table {
    string table_id = 1; // 桌子ID
    string name = 2; // 桌子名称
    repeated Seat seats = 3; // 坐位信息
    TableState state = 4; // 桌子状态
}

// 坐位状态
enum SeatState {
    SEAT_IDLE = 0; // 坐位空闲
    SEAT_OCCUPY = 1; // 坐位已占用（必须存在玩家）
    SEAT_READY = 2; // 坐位准备就绪
    SEAT_GAMING = 3; // 坐位正在游戏中
}

// 坐位信息
message Seat {
    uint32 index = 1; // 坐位序号
    string name = 2; // 坐位名称
    SeatState state = 3; // 坐位状态
    string player_id = 4; // 玩家ID
}

// 加入桌子请求
message JoinTableReq {
    string table_id = 1; // 桌子ID
}


// 请求加入响应
message JoinTableResp {
    int32 code = 1; // 结果码
    Table table = 2; // 桌子状态
}

// 坐下请求
message SitDownReq {
    uint32 index = 1; // 坐位序号
}


// 坐下响应
message SitDownResp {
    int32 code = 1; // 结果码
    uint32 index = 2; // 坐位序号
}

// 坐位状态通知
message SeatStateNtf {
    uint32 index = 2; // 坐位序号
    SeatState state = 3; // 坐位状态
    string player_id = 1; // 玩家ID
}

// 踢出码
enum KickOutCode {
    KICK_OUT_OK = 0; // 正常踢出
}

// 踢出通知
message KickOutNtf {
    KickOutCode code = 1;
}

// 客户端上行协议(Req/Res处于同一索引)
message ClientProtocol {
    oneof message {
        SitDownReq sit_down_req = 1; // 请求坐下
    }
}

// 服务端下行协议
message ServerProtocol {
    oneof message {
        SitDownResp sit_down_resp = 1; // 坐下响应
        SeatStateNtf seat_state_ntf = 101; // 坐位状态通知
        KickOutNtf kick_out_ntf = 102; // 踢出通知
    }
}

/// 协议说明
// 1. 请求加入桌子时，发送 JoinTableReq 消息
// 2. 服务端如果失败返回 JoinTableResp 消息，包含结果码及桌子信息
// 3. 客户端加入后发起 SitDownReq 消息，请求坐下
