[package]
name = "vela-table"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

[dependencies]
prost.workspace = true
prost-types.workspace = true
futures.workspace = true
thiserror.workspace = true
volans = { workspace = true, features = ["swarm", "codec"] }
tracing.workspace = true
vela-core.workspace = true
futures-timer.workspace = true
futures-bounded.workspace = true

[build-dependencies]
prost-build = "0.14.1"
